# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 10
  
[[main]]
  name = "Weeds ID"
  url = "weed/"
  identifier = "weed"
  weight = 20
  
[[main]]
  name = "Talks"
  url = "#talks"
  weight = 30

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
 [[main]]
    name = "Meu CV"
    url = "media/Anunciato_CV.pdf"
    identifier = "meu cv"
    weight = 40
    
 [[main]]
  name = "Posters and oral presentation"
  url = "media/Anunciato_PresentationPosters"
  parent = "meu cv"
  weight = 1
  
 [[main]]
  name = "Extension publications"
  url = "media/Anunciato_extension"
  parent = "meu cv"
  weight = 2
